### PR TITLE
Added "dialogEnabled" attribute to enable/disable custom value input dialog

### PR DESCRIPTION
**Pull request by makiftutuncu**
Hi there, cool library!

In my project, I wanted to disable custom input dialog but there was no way to do so. So I added a new attribute to easily enable/disable custom input dialog both via XML attributes and java methods.

I hope you'll merge this so I can update my dependency and start using it.

Thanks.

### CODE REVIEW

**Comment by MrBIMC** [comment]
Looks good. However, I'd also remove underline below valueHolder in case if customInputDialog is not enabled. 

I'll merge your PR when will have time.

**Comment by makiftutuncu** [comment]
Sounds reasonable. I think README.md should also be updated to include the new attribute should this PR be merged. I'll also have a look tomorrow. Thanks again. :)

**Comment by MrBIMC** [comment]
Well, I decided to implement it before sleep. Made valueHolder to not to display underline and not be clickable when dialog is disabled. 

Will update docs and release 2.2.0 tomorrow!

**Comment by makiftutuncu** [comment]
Awesome!

**Pull request merged**
